# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.17.13
moddev_version = 2.0.80
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.8.0
remapcheck_version = 0.3.4

# Fabric Properties
# Check these on https://fabricmc.net/develop
java_version=25
minecraft_version = 26.2
fabric_loader_version = 0.19.3
fabric_kotlin_version = 1.13.12+kotlin.2.4.0

# Mod Properties
project_version = 2.0.99+26.2.daleydeng.1
maven_group = io.github.daleydeng.graphlib
archives_base_name = graphlib
javadoc_package_name = com/kneelawk/graphlib

# Dependencies
fapi_version = 0.154.2+26.2
codextra_version = 2.0.0+26.2.daleydeng.1
common_events_version = 1.4.0+26.2.daleydeng.1
lns_version = 0.13.0-pre.1
kml_version = 0.4.3+1.21
knet_version = 1.0.2+1.21

# Runtime Only Dependencies
mod_menu_version = 14.0.0-rc.2

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
